### PR TITLE
Update

### PR DESCRIPTION
**Pull request by EmanuelObredor18**
Hi everyone! Here my code :)

### CODE REVIEW

**Review by Wilmernicolas1700 — APPROVED** [review]
you have done a good job @LonelyWalker17 congratulations

**Review by Wilmernicolas1700 — APPROVED** [review]
good job

**Review by GoJhon — CHANGES_REQUESTED** [review]
@LonelyWalker17 good job! please put the "Activity_3" folder inside "Emanuel_Obredor" folder

**Comment by EmanuelObredor18** [comment]
Code ready @GoJhon

**Review by GoJhon — CHANGES_REQUESTED** [review]
@LonelyWalker17 Thank you for organize folder, but now you need to put "codigo.md" inside "Emanuel_Obredor" folder.

**Comment by EmanuelObredor18** [comment]
> 

@GoJhon this is done. Check it.

**Pull request closed without merging**
