### PR TITLE
Extends-Activity

### PR DESCRIPTION
**Pull request by EmanuelObredor18**
Hi everybody. Here I leave my code.

### CODE REVIEW

**Review by FabioP0 — CHANGES_REQUESTED** [review]
Good job, I just need to put the link in the resume.

**Comment by EmanuelObredor18** [comment]
> Good job, I just need to put the link in the resume.

Done @FabioP0

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
excellent algorithm

**Review by FabioP0 — APPROVED** [review]
Good work, keep it up.

**Review by Jxze18 — APPROVED** [review]
good work

**Pull request merged**
