### PR TITLE
exercise search

### PR DESCRIPTION
**Pull request by GoJhon**
Hello, have a good day. I send my search exercise. Enjoy it.

### CODE REVIEW

**Review by LuisJrDev — APPROVED** [review]
Excellent your work, I liked the structure of your algorithm, Very good @GoJhon

**Review by EmanuelObredor18 — APPROVED** [review]
Nice code. It hasn't syntax errors. Great job @GoJhon

**Review by Jesusvillanueva07 — APPROVED** [review]
excellent work as always @GoJhon  good work.

**Review by Wilmernicolas1700 — APPROVED** [review]
you have a good code @GoJhon  keep it up

**Review by JuanDavid0630 — APPROVED** [review]
Good work, keep it up

**Pull request merged**
