### PR TITLE
Ejercicioo2

### PR DESCRIPTION
**Pull request by Wilmernicolas1700**
Good night. I did remodeling of an exercise, I hope and can accept it

### CODE REVIEW

**Review by FabioP0 — CHANGES_REQUESTED** [review]
You only uploaded one file, please check and re-upload

**Review by FabioP0 — APPROVED** [review]
Well done.

**Review by CamiloLafaurie — APPROVED** [review]
good work @Wilmernicolas1700 keep up the good work

**Review by Jxze18 — APPROVED** [review]
good job

**Pull request merged**
