### PR TITLE
Ejercicioo2

### PR DESCRIPTION
**Pull request by Wilmernicolas1700**
Good evening, I am sending my work evidence with dart

### CODE REVIEW

**Review by FabioP0 — CHANGES_REQUESTED** [review]
Very good job, but remember to put the link of the exercise in the resume.

**Review by FabioP0 — APPROVED** [review]
Good job.

**Review by Jxze18 — APPROVED** [review]
good work

**Review by CamiloLafaurie — APPROVED** [review]
very good work @Wilmernicolas1700  but I recommend you to use less spaces that way you save a couple of lines.

**Pull request merged**
