### PR TITLE
Dart

### PR DESCRIPTION
**Pull request by jvidesDev**
Exercise wearing extends, implements and abstract.

### CODE REVIEW

**Review by CamiloLafaurie — COMMENTED** [review]
good job @JuanCito16

**Review by CamiloLafaurie — APPROVED** [review]

**Review by CamiloLafaurie — APPROVED** [review]
good coding we invite you to keep improving your future coding.

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good work

**Review by Jxze18 — APPROVED** [review]
good job

**Pull request merged**
