### PR TITLE
Ejercicios

### PR DESCRIPTION
**Pull request by CamiloLafaurie**
good evening, this time I present the algorithm that allows us to search for an identification and this previously registered.

### CODE REVIEW

**Review by Wilmernicolas1700 — APPROVED** [review]
well done @CamiloLafaurie

**Review by EmanuelObredor18 — COMMENTED** [review]
Well done @CamiloLafaurie

**Review by EmanuelObredor18 — APPROVED** [review]

**Review by GoJhon — CHANGES_REQUESTED** [review]
@CamiloLafaurie good job, but there is a mistake in your flowchart, you need to add a flow between the "prom=recaudo_total/abono" process and ""total recaudo es de $", abono" display and remember it's no neccesary writes "esc" in the flowchart. 

Mistake

**Review by Luisafernanda29 — CHANGES_REQUESTED** [review]
good code, but in your first code it should be "prom = recaudo_final / abono".

**Pull request closed without merging**
