### PR TITLE
exercise 2

### PR DESCRIPTION
**Pull request by JuanDavid0630**
exercise of the day 14/09/2022

### CODE REVIEW

**Review by Luisafernanda29 — APPROVED** [review]
Good job!

**Review by GoJhon — APPROVED** [review]
@JuanDavid0630 Good job! you have a nice logic.. keep it up!

**Review by Jesusvillanueva07 — APPROVED** [review]
good work

**Review by Jxze18 — APPROVED** [review]
excellent work keep it up

**Review by FabioP0 — CHANGES_REQUESTED** [review]
good code, but you must update links

**Review by hguzman — APPROVED** [review]
Ok

**Pull request merged**
