### PR TITLE
developing

### PR DESCRIPTION
**Pull request by CamiloLafaurie**
welcome, I am enclosing proof of what you have learned in class, I look forward to hearing from you.

### CODE REVIEW

**Review by EmanuelObredor18 — APPROVED** [review]
Hi Camilo. Great job on your code. It's easy to understand and run perfectly. Congratulations.

**Review by LuisJrDev — CHANGES_REQUESTED** [review]
Good @CamiloLafaurie, in the flowchart you have not connected the variable "prom" with the (esc "total recaudado", recaudado).

**Review by Jesusvillanueva07 — APPROVED** [review]
hello @CamiloLafaurie  good job.

**Review by LuisJrDev — APPROVED** [review]
Good Job @CamiloLafaurie

**Review by Fernando1007 — APPROVED** [review]
Good job @CamiloLafaurie

**Pull request closed without merging**
