### PR TITLE
upgrade

### PR DESCRIPTION
**Pull request by RonaldoGomezCastro2558427**
then I upload the pending evidence of the 2 quarter

### CODE REVIEW

**Review by CamiloLafaurie — APPROVED** [review]
@RonaldoGomezCastro2558427 very good job and organization

**Review by jvidesDev — APPROVED** [review]
Good job

**Review by juanhsd — APPROVED** [review]
please create the readme and check the links

**Review by juanhsd — CHANGES_REQUESTED** [review]
please create the readme and check the links

**Pull request merged**
