### PR TITLE
new exercise

### PR DESCRIPTION
**Pull request by Jaidercamiloo**
here is my exercise number 2

### CODE REVIEW

**Review by Luisafernanda29 — CHANGES_REQUESTED** [review]
good job, but in your condition it should be "cedula =..." and you should assign a variable to the first msgbox.

**Review by FabioP0 — APPROVED** [review]
Good job.

**Review by Jxze18 — APPROVED** [review]
very good

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good job

**Review by CamiloLafaurie — APPROVED** [review]
good job

**Pull request merged**
