### PR TITLE
Update exercise 5

### PR DESCRIPTION
**Pull request by andresdtd**
This is the update of the exercise constructor and the correction on the indeted exercise 4, please review, thanks.

### CODE REVIEW

**Review by CamiloLafaurie — APPROVED** [review]
good work partner

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good job

**Review by Jxze18 — APPROVED** [review]
ecxellent work

**Review by FabioP0 — APPROVED** [review]
Well done.

**Pull request merged**
