### PR TITLE
exercise4

### PR DESCRIPTION
**Pull request by juanhsd**
update the execise about create class and methods

### CODE REVIEW

**Review by FabioP0 — APPROVED** [review]
Good job.

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good job

**Review by Jxze18 — APPROVED** [review]

**Review by Jxze18 — APPROVED** [review]
nice exercise

**Review by CamiloLafaurie — APPROVED** [review]
good job

**Comment by andresdtd** [comment]
well done bro!!!

**Pull request merged**
