### PR TITLE
exercise

### PR DESCRIPTION
**Pull request by Cesar1520**
I deliver exercise number 4

### CODE REVIEW

**Review by FabioP0 — CHANGES_REQUESTED** [review]
Good morning @Cesar1520 , in your folder you can only see "ejercicio4.md" and "ejercicio_3.md", the other exercises seem to have been renamed and cannot be viewed.

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good work

**Review by Jxze18 — APPROVED** [review]
ecxellent work

**Review by Jxze18 — APPROVED** [review]
good job

**Review by CamiloLafaurie — APPROVED** [review]
good work @Cesar1520 keep up the good work

**Review by FabioP0 — APPROVED** [review]

**Pull request merged**
