### PR TITLE
Update pull request

### PR DESCRIPTION
**Pull request by GoJhon**
I organized my old codes and I included the newest activity (Background widget).

### CODE REVIEW

**Review by juanhsd — APPROVED** [review]
Checked

**Review by CamiloLafaurie — CHANGES_REQUESTED** [review]
you must place the link in the folder named aprendices

**Comment by GoJhon** [comment]
@CamiloLafaurie if you can see, the commit e91b481 "Fix comand", there is a update of my apprentice link. Please verify the commit. If you don't know see a commit, I send a direct link: https://github.com/hguzman/ADSO2558427/tree/e91b4810d06e1bf24235ccadbf43fea4c8b14a96

**Review by CamiloLafaurie — APPROVED** [review]
Good Job @GoJhon

**Review by Luisafernanda29 — APPROVED** [review]
well done.

**Pull request merged**
