### PR TITLE
Exercise 4, Dart

### PR DESCRIPTION
**Pull request by LuisJrDev**
I send the fourth and first activity on dart, thanks

### CODE REVIEW

**Review by CamiloLafaurie — APPROVED** [review]
good work, I invite you to keep on improving

**Review by Jxze18 — APPROVED** [review]
ecxellent work

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good job

**Review by FabioP0 — APPROVED** [review]
Well done.

**Pull request merged**
