### PR TITLE
Update exercise 4

### PR DESCRIPTION
**Pull request by andresdtd**
This is the dart exercise, please review, thanks.

### CODE REVIEW

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Goog job

**Review by CamiloLafaurie — APPROVED** [review]
good job

**Review by FabioP0 — APPROVED** [review]
Good job. 👍🏻

**Review by JuanDavid0630 — APPROVED** [review]
Good joob!

**Review by Jxze18 — APPROVED** [review]
nice job

**Pull request merged**
