### PR TITLE
Ejercicio 2

### PR DESCRIPTION
**Pull request by LuisJrDev**
Good afternoon, I sent exercise 2 on name search with identification cards

### CODE REVIEW

**Comment by LuisJrDev** [comment]
I have some corrections from previous works but only change the names of the files

**Review by GoJhon — APPROVED** [review]
Hello @Luislemus0109. I checked your code and it's incredible. good indented and awesome logic. Keep it up!

**Review by Jesusvillanueva07 — APPROVED** [review]
well done @Luislemus0109  very good job.

**Review by Wilmernicolas1700 — APPROVED** [review]
Good Job!!

**Review by EmanuelObredor18 — APPROVED** [review]
Nice code @Luislemus0109

**Review by hguzman — APPROVED** [review]
OK

**Pull request merged**
