### PR TITLE
Dart

### PR DESCRIPTION
**Pull request by LuisJrDev**
I send the two dart exercises, about inheritance...
and I delete an old folder that was mine but I don't use it.

### CODE REVIEW

**Review by FabioP0 — APPROVED** [review]

**Review by FabioP0 — APPROVED** [review]
good code, well done.

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Excellent work, keep it up

**Review by Jxze18 — APPROVED** [review]
very good job

**Review by CamiloLafaurie — APPROVED** [review]
good code we invite you to keep it up

**Pull request merged**
