### PR TITLE
Ciclo while

### PR DESCRIPTION
**Pull request by FabioP0**
Here is my activity.

### CODE REVIEW

**Review by GoJhon — COMMENTED** [review]
Hello @FabioP0 , good job. You need to change a figure in the flowchart; "El estudiante no aporto" is a display.

**Comment by FabioP0** [comment]
I already fixed the diagram. 👍

**Review by GoJhon — APPROVED** [review]
Good job Fabio

**Review by juanhsd — APPROVED** [review]
Nice job!
Check the indentation of the beginning.

**Review by andresdtd — CHANGES_REQUESTED** [review]
Good code and diagram @FabioP0, just please indent in the beginning of the code.

**Review by andresdtd — APPROVED** [review]
Now is perfect, good job @FabioP0

**Review by hguzman — APPROVED** [review]

**Pull request merged**
