### PR TITLE
evidence number 2

### PR DESCRIPTION
**Pull request by RonaldoGomezCastro2558427**
Good morning, I am sending you the development of evidence #2 of 09/16/2022, I await your response.

### CODE REVIEW

**Review by JuanDavid0630 — APPROVED** [review]
Good work

**Review by Luisafernanda29 — APPROVED** [review]
good code!

**Review by GoJhon — CHANGES_REQUESTED** [review]
Hello @RonaldoGomezCastro2558427 good job! you have a nice indented and excelent logic. You need to add a new link in your hojadedatos.md

**Review by EmanuelObredor18 — APPROVED** [review]
I approve this. Good job @RonaldoGomezCastro2558427 .

**Pull request merged**
