### PR TITLE
I request review

### PR DESCRIPTION
**Pull request by Cristian-pacheco**
request review

### CODE REVIEW

**Review by GoJhon — APPROVED** [review]
@Cristian-pacheco Good job! you have a nice logic. In the search exercise, the software must to search the ID people and prints the name, but it's alright. Keep it up!

**Review by EmanuelObredor18 — APPROVED** [review]
Nice code @Cristian-pacheco . Keep it up.

**Comment by Cristian-pacheco** [comment]
I request review

**Comment by Cristian-pacheco** [comment]
I request review

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good job

**Review by Jxze18 — APPROVED** [review]
ecxellent keep it up

**Review by hguzman — APPROVED** [review]
Autorizado por los revisores

**Pull request closed without merging**
