### PR TITLE
activity and resume

### PR DESCRIPTION
**Pull request by andresg122**
I have created a folder where my exercise and resume.

### CODE REVIEW

**Review by LuisJrDev — APPROVED** [review]
Good evening @andresg122 , I see that in your flowchart you are assigning the variable "how much will you pay?" It would be ("how much are you going to pay?", f ).... Just that correction, the rest is fine.

**Review by GoJhon — APPROVED** [review]
@andresg122 good job!

**Review by Jesusvillanueva07 — APPROVED** [review]
good job @andresg122

**Review by jvidesDev — APPROVED** [review]
Very good code

**Pull request merged**
