### PR TITLE
processed work

### PR DESCRIPTION
**Pull request by andresfelipeatenciomendoza**
good morning I present my work

### CODE REVIEW

**Review by EmanuelObredor18 — CHANGES_REQUESTED** [review]
Hello Andrés, I hope you have a nice night.

Regarding your code, it had some small errors in the writing of the MsgBox and in the limit of the While. I helped you with these errors. However, this is not the only error it keeps. I invite you to review the While of your flowchart.

When you've done it correctly, I'll approve your branch.

**Review by GoJhon — CHANGES_REQUESTED** [review]
@andresfelipeatenciomendoza please create a new branch for pull request. This pull request is into main from main.

**Review by EmanuelObredor18 — APPROVED** [review]

**Review by Jxze18 — APPROVED** [review]
very good

**Review by CamiloLafaurie — APPROVED** [review]
good @andresfelipeatenciomendoza I recommend that at the time of making the flowchart separate a little more the first boxes so that the arrows are seen better. likewise we invite you to continue improving your code.

**Review by FabioP0 — CHANGES_REQUESTED** [review]
Good morning @andresfelipeatenciomendoza, the files you uploaded look good, now you just have to upload it to your branch and not in your main, you must also update the links in your resume. Thank you.

**Pull request closed without merging**
