### PR TITLE
Exercise 3, Data search with cedula

### PR DESCRIPTION
**Pull request by LuisJrDev**
Good afternoon, I am sending activity #3 and making corrections to my resume

### CODE REVIEW

**Review by GoJhon — APPROVED** [review]
@Luislemus0109 you have a excelent code. Keep it up!

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good Job!!

**Review by CamiloLafaurie — APPROVED** [review]
good job

**Review by hguzman — APPROVED** [review]
Ok

**Pull request merged**
