### PR TITLE
Create ejercicio2.md

### PR DESCRIPTION
**Pull request by Wilmernicolas1700**
good afternoon, I send the second exercise of the cycle while, I wait and do review. I remain attentive to your answers

### CODE REVIEW

**Review by GoJhon — APPROVED** [review]
@Wilmernicolas1700 nice logic and code. Keep it up!

**Review by GoJhon — CHANGES_REQUESTED** [review]
@Wilmernicolas1700 Good job. Remember, you need to add a link in "Hoja de vida".

**Review by GoJhon — APPROVED** [review]
@Wilmernicolas1700 good job! keep it up!

**Review by LuisJrDev — APPROVED** [review]
Good Job!! @Wilmernicolas1700

**Review by EmanuelObredor18 — APPROVED** [review]
Excellent code @Wilmernicolas1700.

**Review by jvidesDev — APPROVED** [review]
Good code @Wilmernicolas1700

**Pull request merged**
