### PR TITLE
Exercise2

### PR DESCRIPTION
**Pull request by andresdtd**
Check the exercise, thanks.

### CODE REVIEW

**Review by LuisJrDev — APPROVED** [review]
Excellent work @andresdtd, Excellent logic.... Perfect

**Review by EmanuelObredor18 — APPROVED** [review]
Approved. Excellent job @andresdtd :)

**Review by GoJhon — APPROVED** [review]
Hello @andresdtd, good job!

**Comment by Jesusvillanueva07** [comment]
hello @andresdtd good job.

**Review by Luisafernanda29 — APPROVED** [review]
good job!

**Pull request merged**
