### PR TITLE
exercise while

### PR DESCRIPTION
**Pull request by Developeryezid**
Good morning, I present my while loop job

### CODE REVIEW

**Review by GoJhon — CHANGES_REQUESTED** [review]
Hello @Developeryezid. You have a nice logic. In the if "aporto>10000" you need to add a variable "tot=tot + 1" because people give more than $10.000 must to stay in "tot" too. 
In the flowchart, the desicion "abono<400000", it must to be "abono<3000000", finally fix a return flow.

**Comment by Developeryezid** [comment]
@GoJhon good afternoon, correction was made in the flowchart, improvement in the conditional  aporto = 0

**Review by GoJhon — APPROVED** [review]
@Developeryezid I checked your flowchart and I saw the fixed, good job! I recommend you the next time more organization in the return flows.

**Review by juanhsd — APPROVED** [review]
Excellent!

**Review by andresdtd — APPROVED** [review]
Good code and diagram, i like your logic @Developeryezid

**Review by hguzman — APPROVED** [review]

**Pull request merged**
