### PR TITLE
Mora

### PR DESCRIPTION
**Pull request by Breitner12**
new exercise end update

### CODE REVIEW

**Review by CamiloLafaurie — APPROVED** [review]
Good job

**Review by Luisafernanda29 — CHANGES_REQUESTED** [review]
check the readme "ADSO12", it appears empty.

**Review by Luisafernanda29 — APPROVED** [review]
Good job!

**Review by GoJhon — CHANGES_REQUESTED** [review]
@Breitner12  good job, but please organize your folder

**Comment by Breitner12** [comment]
bug fixed

**Review by GoJhon — APPROVED** [review]
@Breitner12 I checked, good job! keep it up!

**Pull request merged**
