### PR TITLE
activity.

### PR DESCRIPTION
**Pull request by andresg122**
hello, I request to add to the project where my activity is, thank you very much.

### CODE REVIEW

**Review by GoJhon — COMMENTED** [review]
Hello @andresg122. I checked you code and it's very organized and very easy for reading, good job. In the flowchart you missed the return flow in the desicion t<=3000000 and the "no" flow needs to arrives on the "pr=t/n" process becuase in your code this proccess is out of the while.

**Review by GoJhon — APPROVED** [review]
I saw your diagram update. Nice job @andresg122. Keep it up

**Review by juanhsd — CHANGES_REQUESTED** [review]
Hi, @andresg122 . You have mistakes in your flowchart, remember that we use the 'screen' to print information. In addition, your code is not indented. 
Finally, try to upload the code on the repository not in your profile.

**Review by andresdtd — CHANGES_REQUESTED** [review]
Hello @andresg122, on the diagram you forget to put the "no" in the (if f>=10000), please fix it, good code though.

**Pull request closed without merging**
