### PR TITLE
exercise 3

### PR DESCRIPTION
**Pull request by juanhsd**
update the last exercise abou data search

### CODE REVIEW

**Review by GoJhon — APPROVED** [review]
Hello @juanhsd, I checked your code and it's excelent. Keep it up!

**Review by CamiloLafaurie — APPROVED** [review]
good job

**Review by JuanDavid0630 — APPROVED** [review]
good joob

**Review by jvidesDev — APPROVED** [review]
excellent!

**Review by Jxze18 — APPROVED** [review]
well done

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]

**Review by FabioP0 — APPROVED** [review]
Well done. 👍🏻

**Pull request merged**
