### PR TITLE
exercise 

### PR DESCRIPTION
**Pull request by Zhxrick**
Good morning, I send the excercise worked on in class.

### CODE REVIEW

**Review by LuisJrDev — APPROVED** [review]
Good afternoon. Everything was very well prepared... Just a recommendation in the variables: do not use capital letters, I see that in the "Recaudo" variable it has a capital letter... Another recommendation can also create a counter for the "Recaudo" variable so that everything what the students enter is saved in that variable, although the program also runs like this, very good job

**Review by GoJhon — APPROVED** [review]
Hello @Zhxrick . I checked your work and it's looks awesome. I have the same recommendation of @Luislemus0109 . Nice work and have good day.

**Review by juanhsd — APPROVED** [review]
Good job

**Review by hguzman — APPROVED** [review]

**Review by hguzman — COMMENTED** [review]
Good Job!!

**Pull request merged**
