### PR TITLE
worked

### PR DESCRIPTION
**Pull request by Jesusvillanueva07**
the exercise was placed while + flowchart + resume Please add.

### CODE REVIEW

**Review by GoJhon — CHANGES_REQUESTED** [review]
Hi @Jesusvillanueva07, I saw your code and it's incredible, good job! The flowchart diagram has a mistake; in the decision "dinero > 0" the "yes" flujo is in the manual input, please fix it.

**Review by andresdtd — APPROVED** [review]
Good job!! @Jesusvillanueva07

**Review by LuisJrDev — CHANGES_REQUESTED** [review]
Please correct the flowchart input ("how much will it take",money)

**Review by Luisafernanda29 — CHANGES_REQUESTED** [review]
nice job, but in your flowchart the if line should come out of the first condition "dinero > 0 ".

**Review by EmanuelObredor18 — CHANGES_REQUESTED** [review]
You have some logic errors in your code and flowchart. Please fix them. After you do this, I'll accept your fork.

**Review by Jxze18 — APPROVED** [review]
excellent work

**Review by Jxze18 — APPROVED** [review]
very good keep it up

**Review by CamiloLafaurie — CHANGES_REQUESTED** [review]
good jesus your code is very good but there is an error in the flowchart in the imput "cuanto quiere abonar" there is no variable assigned to it

**Review by Jxze18 — APPROVED** [review]

**Review by FabioP0 — APPROVED** [review]
good job.

**Review by RonaldoGomezCastro2558427 — APPROVED** [review]
Good work

**Review by CamiloLafaurie — APPROVED** [review]
good job well done.

**Pull request merged**
