### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Zhxrick**
Good morning, please check my files.

### CODE REVIEW

**Review by GoJhon — CHANGES_REQUESTED** [review]
@Zhxrick Please update your direct link in the apprentice list.

**Review by GoJhon — APPROVED** [review]
good job @Zhxrick

**Review by CamiloLafaurie — APPROVED** [review]
good job @Zhxrick  but I recommend that you take the recommendation that the teacher gave us when naming the activities as ADSO #.

**Review by Luisafernanda29 — APPROVED** [review]
Good job!

**Pull request merged**
