### PR TITLE
Create exercise 2

### PR DESCRIPTION
**Pull request by juanhsd**
exercise 2 done

### CODE REVIEW

**Review by LuisJrDev — APPROVED** [review]
Excellent work @juanhsd, Excellent logic.... Perfect

**Review by GoJhon — APPROVED** [review]
@juanhsd good job!

**Review by Jesusvillanueva07 — APPROVED** [review]
excellent job @juanhsd

**Review by EmanuelObredor18 — APPROVED** [review]
I guess I have nothing to say, my colleagues have already said everything. Good work.

**Pull request merged**
