### PR TITLE
New list

### PR DESCRIPTION
**Pull request by juanhsd**

### CODE REVIEW

**Review by andresdtd — APPROVED** [review]

**Review by GoJhon — COMMENTED** [review]
@juanhsd thank you for refreshing the list. Can you erase the space between the name and the link, I think that the some links will don't work by the space, like [Fabio Alberto Poveda]

**Review by GoJhon — APPROVED** [review]
Good job!

**Review by LuisJrDev — APPROVED** [review]
Thank You very much @juanhsd

**Review by EmanuelObredor18 — APPROVED** [review]

**Review by hguzman — APPROVED** [review]
Ok

**Pull request merged**
