### PR TITLE
exercise

### PR DESCRIPTION
**Pull request by angelcastro0923**
Please review exercises, thank you

### CODE REVIEW

**Review by Luisafernanda29 — CHANGES_REQUESTED** [review]
well done, but you have a small error, missing the "]" sign in the database, also check the link "exercise11.md" in the database.

**Review by juanhsd — CHANGES_REQUESTED** [review]
you are not on the apprentices list

**Review by Luisafernanda29 — APPROVED** [review]
Well done!

**Review by juanhsd — APPROVED** [review]

**Review by GoJhon — CHANGES_REQUESTED** [review]
@angelcastro0923 your java activity link is broke

**Review by GoJhon — APPROVED** [review]
good job

**Pull request merged**
