### PR TITLE
Exercise #2

### PR DESCRIPTION
**Pull request by FabioP0**
Here I send the search exercise by ID number. :blush:

### CODE REVIEW

**Review by GoJhon — APPROVED** [review]
@FabioP0 good job! keep it up!

**Review by Luisafernanda29 — APPROVED** [review]
Good job!

**Review by Jesusvillanueva07 — APPROVED** [review]
good job @FabioP0

**Review by JuanDavid0630 — APPROVED** [review]
good job 👍

**Review by jvidesDev — APPROVED** [review]
Good work @FabioP0 , congratulations

**Pull request merged**
