### PR TITLE
Exercise while merge

### PR DESCRIPTION
**Pull request by GoJhon**
Hello mr. Guzman, have a good day. I'm Jhon Santander, your ADSO student. I would like to your check of this exercise. I hope your answer.

### CODE REVIEW

**Review by hguzman — COMMENTED** [review]
Please don't delete my main REDAME.md

**Comment by GoJhon** [comment]
I see my fault and I changed the file and created a list file.

**Review by juanhsd — CHANGES_REQUESTED** [review]
revise the conditions of the select case in the diagram

**Comment by GoJhon** [comment]
I changed the flowchart image

**Review by andresdtd — APPROVED** [review]
Good Job!

**Review by juanhsd — APPROVED** [review]
Checked!

**Review by hguzman — APPROVED** [review]
Good Job!!!

**Pull request merged**
