### PR TITLE
DELIVERY OF MY EXERCISE

### PR DESCRIPTION
**Pull request by Jaidercamiloo**
HERE I SEND MY NEW EXERCISE, CORRECTED

### CODE REVIEW

**Review by GoJhon — CHANGES_REQUESTED** [review]
Hello @Jaidercamiloo. I saw that you fixed the pull request, good job! You have a good code and indented, but you need to complete de flowchart because you need to add the "no" flow in the desicion "y<=3000000", the process "promedio" and the other displays.

**Comment by Jaidercamiloo** [comment]
correction flowchart

**Review by GoJhon — APPROVED** [review]
@Jaidercamiloo I saw you update, good job. Keep it up.

**Review by andresdtd — APPROVED** [review]
Good code and diagram @Jaidercamiloo

**Review by juanhsd — APPROVED** [review]
Well done

**Review by hguzman — APPROVED** [review]

**Pull request merged**
