### PR TITLE
actualizacion

### PR DESCRIPTION
**Pull request by Breitner12**
here is my updated activity

### CODE REVIEW

**Review by GoJhon — APPROVED** [review]
I saw that you fix the merge pull request, good job @Breitner12 !

**Review by juanhsd — CHANGES_REQUESTED** [review]
Hi, @Breitner12 ! 
please, fix code indentation

**Review by andresdtd — APPROVED** [review]
Nice job, @Breitner12

**Comment by Breitner12** [comment]
updated code indentation

**Review by juanhsd — APPROVED** [review]
you did it, well done!

**Review by hguzman — APPROVED** [review]

**Pull request merged**
